"""Type stubs for websockets.asyncio.server."""

from typing import Any

class ServerConnection:
    async def send(self, message: str | bytes) -> None: ...
    async def recv(self) -> str | bytes: ...
    async def close(self) -> None: ...
    @property
    def closed(self) -> bool: ...
    @property
    def remote_address(self) -> tuple[str, int] | None: ...
    def __aiter__(self) -> Any: ...
    async def __anext__(self) -> str | bytes: ...
